-- 코드를 입력하세요
SELECT I_N_C.MONTH AS MONTH, I_N_C.NAME, I_N_C.COUNT
FROM (SELECT DATE_FORMAT(CREATED_AT, '%m') AS MONTH, NAME, COUNT(*) AS COUNT
    FROM PLACES P
    LEFT JOIN PLACE_REVIEWS PR
    ON P.ID = PR.PLACE_ID
    WHERE CREATED_AT BETWEEN CAST('2018-01-01 00:00:00' AS DATE) AND CAST('2018-12-31 23:59:59' AS DATE)
    GROUP BY P.ID, MONTH) I_N_C
LEFT JOIN(
    SELECT MONTH, MAX(COUNT) AS MAX
    FROM(
        SELECT DATE_FORMAT(CREATED_AT, '%m') AS MONTH, P.ID AS ID, NAME, COUNT(*) AS COUNT
        FROM PLACES P
        LEFT JOIN PLACE_REVIEWS PR on P.ID = PR.PLACE_ID
        WHERE CREATED_AT BETWEEN CAST('2018-01-01 00:00:00' AS DATE) AND CAST('2018-12-31 23:59:59' AS DATE)
        GROUP BY ID, MONTH
        ORDER BY MONTH, NAME, COUNT) P_PR
    GROUP BY MONTH) MON_MAX
ON I_N_C.MONTH = MON_MAX.MONTH
WHERE I_N_C.COUNT = MON_MAX.MAX
ORDER BY MONTH, NAME